;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        abort-recursive-edit
        c-electric-backspace
        c-electric-brace
        c-electric-colon
        c-electric-paren
        c-electric-semi&comma
        hungry-delete-backward
        iy-go-to-char
        python-indent-dedent-line-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        minibuffer-complete-and-exit
        mouse-drag-region
        mouse-set-point
        ))
