;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all '(abort-recursive-edit
                               c-electric-paren
                               c-electric-semi&comma
                               c-electric-brace
                               c-electric-backspace))

(setq mc/cmds-to-run-once '(mouse-set-point
                            mouse-drag-region
                            minibuffer-complete-and-exit))

                            
                               